name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install SSH
      run: sudo apt-get install -y ssh

    - name: SSH into server and pull latest changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd D:\Azure\CRUDS
          git pull origin main
          
    - name: Restart Flask application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd D:\Azure\CRUDS
          sudo systemctl restart your-flask-service-name
